config/routes.rb
Rails.application.routes.draw do

  resources :statuses

  resources :appointments do
    collection do
      get 'completed', :as => "completed"
    end
  end

  resources :diagnostics

  resources :states

  get "dashboard/index"

  get "datamanage/index"

  resources :employees

  resources :physicians

  resources :patients

  resources :insurances

  mount Upmin::Engine => '/admin'

  devise_for :users do
    get "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
  end

  resources :users

  root 'home#index'

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base

  belongs_to :patient
  belongs_to :physician
  belongs_to :diagnostic
  belongs_to :status

  validates_uniqueness_of :date, scope: [:physician_id], :message=>"and time is already taken with this physician. Please select another time or physician."

  DateTime.now.new_offset(0)

  after_initialize :defaults

  def defaults
    self.status_id ||= 1 if self.status_id.nil?
    self.diagnostic_id ||= 2029 if self.diagnostic_id.nil?
  end

  def self.totalappointment
    if (:status_id == 4)
    @totalapps = Appointment.count
    end
  end

end

app/models/diagnostic.rb
class Diagnostic < ActiveRecord::Base

  has_many :appointments

end

app/models/employee.rb
class Employee < ActiveRecord::Base

  has_one :user
  belongs_to :state

  def self.emailcheck
    if Patient.where(userid: self.userid).exists? then
      errors.add(:userid,'This email is already in use. Please use another.')
    end
  end
end

app/models/insurance.rb
class Insurance < ActiveRecord::Base

  has_many :patients

end

app/models/patient.rb
class Patient < ActiveRecord::Base

  belongs_to :insurance
  has_many :physicians , :through => :appointments
  has_many :appointments
  has_one :user
  belongs_to :state

  def self.emailcheck
    if Patient.where(userid: self.userid).exists? then
      errors.add(:userid,'This email is already in use. Please use another.')
    end
  end

  def self.emailval
    validates_uniqueness_of :email
  end

  # Donor.joins(:donations).where(:id => params[:id]).sum('value'))


end

app/models/physician.rb
class Physician < ActiveRecord::Base

  has_one :user
  has_many :patients, :through => :appointments
  has_many :appointments
  belongs_to :state

  def self.emailcheck
    if Patient.where(userid: self.userid).exists? then
      errors.add(:userid,'This email is already in use. Please use another.')
    end
  end
end

app/models/state.rb
class State < ActiveRecord::Base

  has_many :patients
  has_many :physicians
  has_many :employees

end

app/models/status.rb
class Status < ActiveRecord::Base

  has_many :appointments

end

app/models/user.rb
class User < ActiveRecord::Base

  belongs_to :patient
  belongs_to :physician
  belongs_to :employee

  enum role: [:admin, :physician, :patient, :employee]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :patient
  end

  def self.emailval
    validates_uniqueness_of :email
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]


  def index
    @employees = Employee.all
    @employees = Employee.paginate(:page => params[:page], :per_page => 15)

  end

  def show
    @employee = Employee.find(params[:id])
  end

  def new
    @employee = Employee.new
  end

  def edit
  end

  def create
    @employee = Employee.new(employee_params)
    @employee.save
    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end

  end

  def update
    @employee.update(employee_params)
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    def set_employee
      @employee = Employee.find(params[:id])
    end

    def employee_params
      params.require(:employee).permit(:name, :address, :city, :zipcode, :phone, :state_id, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!

  def index
    if user_signed_in?
        redirect_to  :controller=>'dashboard', :action => 'index'
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController



  def index
    @users = User.all
    @users = User.order(:role => :asc, :email => :desc).paginate(:page => params[:page], :per_page => 15)

  end

  def show
    @user = User.find(params[:id])

  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    authorize user
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper



end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/helpers/diagnostics_helper.rb
module DiagnosticsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/insurance_helper.rb
module InsuranceHelper
end

app/helpers/insurances_helper.rb
module InsurancesHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/physicians_helper.rb
module PhysiciansHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/employees/_form.html.erb
<% if current_user.employee? %>
    <%= simple_form_for(@employee, :class => "navbar-form navbar-left form-inline form-signin", :role => "form") do |f|%>
        <%= f.label :name, :class => 'login-label' %><br />
        <%= f.collection_select :name, User.all.select{|employee| employee.email == current_user.email},:name, :name, :class => 'form-control' %>
        <br/>
        <%= f.label :address, :class => 'login-label' %><br />
        <%= f.text_field :address, autocomplete: "off", :class => 'form-control'%>
        <%= f.label :city, :class => 'login-label' %><br />
        <%= f.text_field :city, autocomplete: "off", :class => 'form-control'%>
        <%= f.label :state, :class => 'login-label' %><br />
        <%= f.collection_select :state_id, State.all, :id,:state, class: 'btn btn-default' %>
        <br/>
        <%= f.label :zipcode, :class => 'login-label' %><br />
        <%= f.text_field :zipcode, autocomplete: "off", :class => 'form-control'%>
        <%= f.label :phone, :class => 'login-label' %><br />
        <%= f.text_field :phone, autocomplete: "off", :class => 'form-control'%>
        </br></br>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Submit</button>
    <% end %>
<% elsif current_user.admin? %>
    <%= simple_form_for(@employee) do |f| %>
        <%= f.error_notification %>

        <div class="form-inputs">
          <%= f.label :name, :class => 'login-label' %><br />
          <%= f.collection_select :name, Employee.all, :name, :name, :class => 'form-control' %>
          <br/>
          <%= f.label :address, :class => 'login-label' %><br />
          <%= f.text_field :address, autocomplete: "off", :class => 'form-control'%>
          <%= f.label :city, :class => 'login-label' %><br />
          <%= f.text_field :city, autocomplete: "off", :class => 'form-control'%>
          <%= f.label :state, :class => 'login-label' %><br />
          <%= f.collection_select :state_id, State.all, :id,:state, class: 'btn btn-default' %>
          <br/>
          <%= f.label :zipcode, :class => 'login-label' %><br />
          <%= f.text_field :zipcode, autocomplete: "off", :class => 'form-control'%>
          <%= f.label :phone, :class => 'login-label' %><br />
          <%= f.text_field :phone, autocomplete: "off", :class => 'form-control'%>
          </br>
        </div>
        </br>
        <div class="form-actions">
          <%= f.button :submit %>
        </div>
        </br>
    <% end %>

<% end %>

app/views/employees/edit.html.erb
<div class="container">
  <div class="row vertical-offset-100">
    <div class="col-md-4 col-md-offset-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h1>Editing Employee</h1>
          <div class="row-fluid user-row">
          </div>
        </div>
        <div class="panel-body">
          <%= render 'form' %>

          <%= link_to 'Show', @employee %> |
          <%= link_to 'Back', employees_path %>
        </div>
      </div>
    </div>-
  </div>
</div>
</body>
</html>

app/views/employees/index.html.erb
<!--/span-->
<div class="container-fluid">
  <div class="row row-offcanvas row-offcanvas-left">
    <%= render 'shared/sidebar' %>
    <!--/span-->
    <div class="col-xs-12 col-sm-9 content">
      <div class="container">

        <%= will_paginate @employees %>

        <table>
          <thead class="background">
          <tr>
            <th colspan="10">
              Employees Listed
            </th>
          </tr>
          <tr>
            <th>Name</th>
            <th>Address</th>
            <th>City</th>
            <th>State</th>
            <th>Zip Code</th>
            <th>Phone</th>
            <th colspan="3">Actions</th>
          </tr>
          </thead>


  <tbody class="background">
    <% @employees.each do |employee| %>

      <tr>
        <td><%= employee.name %></td>
        <td><%= employee.address %></td>
        <td><%= employee.city %></td>
        <td><%= employee.state.state %></td>
        <td><%= employee.zipcode %></td>
        <td><%= number_to_phone(employee.phone) %></td>
        <td>
          <%= button_to(employee, class: "btn btn-success btn-sm", method: "get")  do %>
              <span class="glyphicon glyphicon-eye-open"></span>
          <% end %>
        </td>
        <td>
          <%= button_to(edit_employee_path(employee), class: "btn btn-info btn-sm", method: "get")  do %>
              <span class="glyphicon glyphicon-edit"></span>
          <% end %>
        </td>
        <td>
          <%= button_to(employee, class: "btn btn-danger btn-sm", method: :delete, data: { confirm: 'Are you sure?' })  do %>
              <span class="glyphicon glyphicon-remove-circle"></span>
              </td>
          <% end %>
          </tr>
  <% end %>
  </tbody>
          <% if current_user.admin? %>
          <div>
            <%= link_to('New Employee', new_employee_path, class: 'btn btn-default', method: 'get') %>
            </br>
            </br>
          </div>
          <% end %>
        </table>
        <br>
        <%= will_paginate @employees %>

        <div class="row vertical-offset-100">



          <div class="col-md-4 col-md-offset-4">

          </div>
        </div>
      </div>
    </div><!--/span-->

  </div><!--/row-->

</div><!-- /.container -->

</body>

app/views/employees/new.html.erb
<div class="container">
  <div class="row vertical-offset-100">
    <div class="col-md-4 col-md-offset-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h1>New Employee</h1>
          <div class="row-fluid user-row">
          </div>
        </div>
        <div class="panel-body">

          <%= render 'form' %>

          <%= link_to 'Back', employees_path %>
        </div>
      </div>
    </div>-
  </div>
</div>
</body>
</html>

app/views/employees/show.html.erb
<body>
<div class="container-fluid">
  <div class="row row-offcanvas row-offcanvas-left">
    <%= render 'shared/sidebar' %>
    <!--/span-->
    <div class="col-xs-12 col-sm-9 content">
      <div class="container">
        <table>
          <thead class="background">
          <tr>
            <th colspan="2">Employee Information</th>
          </tr>
          </thead>

          <tbody class="background">

          <tr>
            <td><strong>Name:</strong></td>
            <td><%= @employee.name %></td>
          </tr>
          <tr>
            <td><strong>Address:</strong></td>
            <td><%= @employee.address %></td>
          </tr>
          <tr>
            <td><strong>City:</strong></td>
            <td><%= @employee.city %></td>
          </tr>
          <tr>
            <td><strong>State:</strong></td>
            <td><%= @employee.state.state %></td>
          </tr>
          <tr>
            <td><strong>Zip Code:</strong></td>
            <td><%= @employee.zipcode %></td>
          </tr>
          <tr>
            <td><strong>Phone:</strong></td>
            <td><%= number_to_phone(@employee.phone) %></td>
          </tr>
          </tbody>
        </table>
        <br/>


        <%= link_to 'Edit', edit_employee_path(@employee) %> |
        <%= link_to 'Back', employees_path %>
      </div>
    </div>
  </div><!--/span-->

</div><!--/row-->

</div><!-- /.container -->

</body>