config/routes.rb
Rails.application.routes.draw do

  resources :statuses

  resources :appointments do
    collection do
      get 'completed', :as => "completed"
    end
  end

  resources :diagnostics

  resources :states

  get "dashboard/index"

  get "datamanage/index"

  resources :employees

  resources :physicians

  resources :patients

  resources :insurances

  mount Upmin::Engine => '/admin'

  devise_for :users do
    get "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
  end

  resources :users

  root 'home#index'

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base

  belongs_to :patient
  belongs_to :physician
  belongs_to :diagnostic
  belongs_to :status

  validates_uniqueness_of :date, scope: [:physician_id], :message=>"and time is already taken with this physician. Please select another time or physician."

  DateTime.now.new_offset(0)

  after_initialize :defaults

  def defaults
    self.status_id ||= 1 if self.status_id.nil?
    self.diagnostic_id ||= 2029 if self.diagnostic_id.nil?
  end

  def self.totalappointment
    if (:status_id == 4)
    @totalapps = Appointment.count
    end
  end

end

app/models/diagnostic.rb
class Diagnostic < ActiveRecord::Base

  has_many :appointments

end

app/models/employee.rb
class Employee < ActiveRecord::Base

  has_one :user
  belongs_to :state

  def self.emailcheck
    if Patient.where(userid: self.userid).exists? then
      errors.add(:userid,'This email is already in use. Please use another.')
    end
  end
end

app/models/insurance.rb
class Insurance < ActiveRecord::Base

  has_many :patients

end

app/models/patient.rb
class Patient < ActiveRecord::Base

  belongs_to :insurance
  has_many :physicians , :through => :appointments
  has_many :appointments
  has_one :user
  belongs_to :state

  def self.emailcheck
    if Patient.where(userid: self.userid).exists? then
      errors.add(:userid,'This email is already in use. Please use another.')
    end
  end

  def self.emailval
    validates_uniqueness_of :email
  end

  # Donor.joins(:donations).where(:id => params[:id]).sum('value'))


end

app/models/physician.rb
class Physician < ActiveRecord::Base

  has_one :user
  has_many :patients, :through => :appointments
  has_many :appointments
  belongs_to :state

  def self.emailcheck
    if Patient.where(userid: self.userid).exists? then
      errors.add(:userid,'This email is already in use. Please use another.')
    end
  end
end

app/models/state.rb
class State < ActiveRecord::Base

  has_many :patients
  has_many :physicians
  has_many :employees

end

app/models/status.rb
class Status < ActiveRecord::Base

  has_many :appointments

end

app/models/user.rb
class User < ActiveRecord::Base

  belongs_to :patient
  belongs_to :physician
  belongs_to :employee

  enum role: [:admin, :physician, :patient, :employee]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :patient
  end

  def self.emailval
    validates_uniqueness_of :email
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!

  def index
    if user_signed_in?
        redirect_to  :controller=>'dashboard', :action => 'index'
    end
  end

end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @statuses = Status.all
    @diagnostics = Diagnostic.paginate(:page => params[:page], :per_page => 20)
    respond_with(@statuses)
  end

  def show
    respond_with(@status)
  end

  def new
    @status = Status.new
    respond_with(@status)
  end

  def edit
  end

  def create
    @status = Status.new(status_params)
    @status.save
    respond_with(@status)
  end

  def update
    @status.update(status_params)
    respond_with(@status)
  end

  def destroy
    @status.destroy
    respond_with(@status)
  end

  private
    def set_status
      @status = Status.find(params[:id])
    end

    def status_params
      params.require(:status).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper



end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/helpers/diagnostics_helper.rb
module DiagnosticsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/insurance_helper.rb
module InsuranceHelper
end

app/helpers/insurances_helper.rb
module InsurancesHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/physicians_helper.rb
module PhysiciansHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/statuses/_form.html.erb
<%= simple_form_for(@status) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/statuses/edit.html.erb
<div class="container">
  <div class="row vertical-offset-100">
    <div class="col-md-4 col-md-offset-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h1>Editing Status</h1>
          <div class="row-fluid user-row">
          </div>
        </div>
        <div class="panel-body">
          <%= render 'form' %>

        </div>
      </div>
    </div>-
  </div>
</div>
</body>
</html>

app/views/statuses/index.html.erb
<div class="container-fluid">
  <div class="row row-offcanvas row-offcanvas-left">
    <%= render 'shared/sidebar' %>
    <!--/span-->
    <div class="col-xs-12 col-sm-9 content">
      <div class="container">

        <div>
          <br/>
          <%= link_to('New Status', new_status_path, class: 'btn btn-default', method: 'get') %>
          </br>
          </br>
        </div>


        <table>
          <thead class="background">
          <tr>
            <th colspan="8">
              Statuses Listed
            </th>
          </tr>
          <tr>
            <th>Status</th>
            <th colspan="3">Actions</th>
          </tr>
          </thead>


          <tbody>
          <% @statuses.each do |status| %>
              <tr>
                <td><%= status.name %></td>
                <td>
                  <%= button_to(status, class: "btn btn-success btn-sm", method: "get")  do %>
                      <span class="glyphicon glyphicon-eye-open"></span>
                  <% end %>
                </td>
                <td>
                  <%= button_to(edit_status_path(status), class: "btn btn-info btn-sm", method: "get")  do %>
                      <span class="glyphicon glyphicon-edit"></span>
                  <% end %>
                </td>
                <td>
                  <%= button_to(status, class: "btn btn-danger btn-sm", method: :delete, data: { confirm: 'Are you sure?' })  do %>
                      <span class="glyphicon glyphicon-remove-circle"></span>
                      </td>
                  <% end %>
                  </tr>
          <% end %>
          </tbody>
        </table>



        <br/>


      </div>
    </div><!--/span-->
  </div><!--/row-->
</div><!-- /.container -->

app/views/statuses/new.html.erb
<div class="container">
  <div class="row vertical-offset-100">
    <div class="col-md-4 col-md-offset-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h1>New Status</h1>
          <div class="row-fluid user-row">
          </div>
        </div>
        <div class="panel-body">
          <%= render 'form' %>

        </div>
      </div>
    </div>-
  </div>
</div>
</body>
</html>

app/views/statuses/show.html.erb
<body>
<div class="container-fluid">
  <div class="row row-offcanvas row-offcanvas-left">
    <%= render 'shared/sidebar' %>
    <!--/span-->
    <div class="col-xs-12 col-sm-9 content">
      <div class="container">
        <table>
          <thead class="background">
          <tr>
            <th colspan="2">Status Information</th>
          </tr>
          </thead>

          <tbody class="background">

          <tr>
            <td><strong>Status:</strong></td>
            <td><%= @status.name %></td>
          </tr>
          </tbody>
        </table>
        <br/>


        <%= link_to 'Edit', edit_status_path(@status) %> |
        <%= link_to 'Back', statuses_path %>
      </div>
    </div>
  </div><!--/span-->

</div><!--/row-->

</div><!-- /.container -->

</body>