config/routes.rb
Rails.application.routes.draw do

  resources :statuses

  resources :appointments do
    collection do
      get 'completed', :as => "completed"
    end
  end

  resources :diagnostics

  resources :states

  get "dashboard/index"

  get "datamanage/index"

  resources :employees

  resources :physicians

  resources :patients

  resources :insurances

  mount Upmin::Engine => '/admin'

  devise_for :users do
    get "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
  end

  resources :users

  root 'home#index'

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base

  belongs_to :patient
  belongs_to :physician
  belongs_to :diagnostic
  belongs_to :status

  validates_uniqueness_of :date, scope: [:physician_id], :message=>"and time is already taken with this physician. Please select another time or physician."

  DateTime.now.new_offset(0)

  after_initialize :defaults

  def defaults
    self.status_id ||= 1 if self.status_id.nil?
    self.diagnostic_id ||= 2029 if self.diagnostic_id.nil?
  end

  def self.totalappointment
    if (:status_id == 4)
    @totalapps = Appointment.count
    end
  end

end

app/models/diagnostic.rb
class Diagnostic < ActiveRecord::Base

  has_many :appointments

end

app/models/employee.rb
class Employee < ActiveRecord::Base

  has_one :user
  belongs_to :state

  def self.emailcheck
    if Patient.where(userid: self.userid).exists? then
      errors.add(:userid,'This email is already in use. Please use another.')
    end
  end
end

app/models/insurance.rb
class Insurance < ActiveRecord::Base

  has_many :patients

end

app/models/patient.rb
class Patient < ActiveRecord::Base

  belongs_to :insurance
  has_many :physicians , :through => :appointments
  has_many :appointments
  has_one :user
  belongs_to :state

  def self.emailcheck
    if Patient.where(userid: self.userid).exists? then
      errors.add(:userid,'This email is already in use. Please use another.')
    end
  end

  def self.emailval
    validates_uniqueness_of :email
  end

  # Donor.joins(:donations).where(:id => params[:id]).sum('value'))


end

app/models/physician.rb
class Physician < ActiveRecord::Base

  has_one :user
  has_many :patients, :through => :appointments
  has_many :appointments
  belongs_to :state

  def self.emailcheck
    if Patient.where(userid: self.userid).exists? then
      errors.add(:userid,'This email is already in use. Please use another.')
    end
  end
end

app/models/state.rb
class State < ActiveRecord::Base

  has_many :patients
  has_many :physicians
  has_many :employees

end

app/models/status.rb
class Status < ActiveRecord::Base

  has_many :appointments

end

app/models/user.rb
class User < ActiveRecord::Base

  belongs_to :patient
  belongs_to :physician
  belongs_to :employee

  enum role: [:admin, :physician, :patient, :employee]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :patient
  end

  def self.emailval
    validates_uniqueness_of :email
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!

  def index
    if user_signed_in?
        redirect_to  :controller=>'dashboard', :action => 'index'
    end
  end

end

app/controllers/insurances_controller.rb
class InsurancesController < ApplicationController
  before_action :set_insurance, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @insurances = Insurance.all
    @insurances = Insurance.paginate(:page => params[:page], :per_page => 15)
    respond_with(@insurances)
  end

  def show
    respond_with(@insurance)
  end

  def new
    @insurance = Insurance.new
    respond_with(@insurance)
  end

  def edit
  end

  def create
    @insurance = Insurance.new(insurance_params)
    @insurance.save
    respond_with(@insurance)
  end

  def update
    @insurance.update(insurance_params)
    respond_with(@insurance)
  end

  def destroy
    @insurance.destroy
    respond_with(@insurance)
  end

  private
    def set_insurance
      @insurance = Insurance.find(params[:id])
    end

    def insurance_params
      params.require(:insurance).permit(:name, :coverage)
    end
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  before_action :set_state, only: [:show, :edit, :update, :destroy]


  def index
    @states = State.all
    @states = State.order(:state).paginate(:page => params[:page], :per_page => 20)

  end

  def show
  end

  def new
    @state = State.new
  end

  def edit
  end

  def create
    @state = State.new(state_params)
    @state.save
    respond_to do |format|
      if @state.save
        format.html { redirect_to @state, notice: 'State was successfully created.' }
        format.json { render :show, state: :created, location: @state }
      else
        format.html { render :new }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @state.update(appointment_params)
    respond_to do |format|
      if @state.update(appointment_params)
        format.html { redirect_to @state, notice: 'State was successfully updated.' }
        format.json { render :show, status: :ok, location: @state }
      else
        format.html { render :edit }
        format.json { render json: @state.errors, state: :unprocessable_entity }
      end
    end
  end

  def destroy
    @state.destroy
    respond_to do |format|
      format.html { redirect_to states_url, notice: 'State was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    def set_state
      @state = State.find(params[:id])
    end

    def state_params
      params.require(:state).permit(:state)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController



  def index
    @users = User.all
    @users = User.order(:role => :asc, :email => :desc).paginate(:page => params[:page], :per_page => 15)

  end

  def show
    @user = User.find(params[:id])

  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    authorize user
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper



end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/helpers/diagnostics_helper.rb
module DiagnosticsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/insurance_helper.rb
module InsuranceHelper
end

app/helpers/insurances_helper.rb
module InsurancesHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/physicians_helper.rb
module PhysiciansHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/insurances/_form.html.erb
<%= simple_form_for(@insurance) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>
    </br>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
    </br>
<% end %>

app/views/insurances/edit.html.erb
<h1>Editing insurance</h1>

<%= render 'form' %>

<%= link_to 'Show', @insurance %> |
<%= link_to 'Back', insurances_path %>

app/views/insurances/index.html.erb
<div class="container-fluid">
  <div class="row row-offcanvas row-offcanvas-left">
    <%= render 'shared/sidebar' %>
    <!--/span-->
    <div class="col-xs-12 col-sm-9 content">
      <div class="container">
        <%= will_paginate @insurances %>

        <br/>
        <%= link_to('New Insurance', new_insurance_path, class: 'btn btn-default', method: 'get') %>
        <br/>
        <br/>
        <table>
          <thead class="background">
          <tr>
            <th colspan="8">
              Insurances Listed
            </th>
          </tr>
          <tr>
            <th>Insurance</th>
            <th colspan="3">Actions</th>
          </tr>
          </thead>


          <tbody>
          <% @insurances.each do |insurance| %>
              <tr>
                <td><%= insurance.name %></td>
                <td>
                  <%= button_to(insurance, class: "btn btn-success btn-sm", method: "get")  do %>
                      <span class="glyphicon glyphicon-eye-open"></span>
                  <% end %>
                </td>
                <td>
                  <%= button_to(edit_insurance_path(insurance), class: "btn btn-info btn-sm", method: "get")  do %>
                      <span class="glyphicon glyphicon-edit"></span>
                  <% end %>
                </td>
                <td>
                  <%= button_to(insurance, class: "btn btn-danger btn-sm", method: :delete, data: { confirm: 'Are you sure?' })  do %>
                      <span class="glyphicon glyphicon-remove-circle"></span>
                      </td>
                  <% end %>
                  </tr>
          <% end %>
          </tbody>
        </table>
        <%= will_paginate @insurances%>

          <br/>

        <br/>


        <br/>


      </div>
    </div><!--/span-->
  </div><!--/row-->
</div><!-- /.container -->

app/views/insurances/new.html.erb
<h1>New insurance</h1>

<%= render 'form' %>

<%= link_to 'Back', insurances_path %>

app/views/insurances/show.html.erb
<body>
<div class="container-fluid">
  <div class="row row-offcanvas row-offcanvas-left">
    <%= render 'shared/sidebar' %>
    <!--/span-->
    <div class="col-xs-12 col-sm-9 content">
      <div class="container">
        <table>
          <thead class="background">
          <tr>
            <th colspan="2">Insurance Information</th>
          </tr>
          </thead>

          <tbody class="background">

          <tr>
            <td><strong>Insurance:</strong></td>
            <td><%= @insurance.name %></td>
          </tr>
          </tbody>
        </table>
        <br/>


        <%= link_to 'Edit', edit_insurance_path(@insurance) %> |
        <%= link_to 'Back', insurances_path %>
      </div>
    </div>
  </div><!--/span-->

</div><!--/row-->

</div><!-- /.container -->

</body>