config/routes.rb
Rails.application.routes.draw do

  resources :statuses

  resources :appointments do
    collection do
      get 'completed', :as => "completed"
    end
  end

  resources :diagnostics

  resources :states

  get "dashboard/index"

  get "datamanage/index"

  resources :employees

  resources :physicians

  resources :patients

  resources :insurances

  mount Upmin::Engine => '/admin'

  devise_for :users do
    get "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
  end

  resources :users

  root 'home#index'

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base

  belongs_to :patient
  belongs_to :physician
  belongs_to :diagnostic
  belongs_to :status

  validates_uniqueness_of :date, scope: [:physician_id], :message=>"and time is already taken with this physician. Please select another time or physician."

  DateTime.now.new_offset(0)

  after_initialize :defaults

  def defaults
    self.status_id ||= 1 if self.status_id.nil?
    self.diagnostic_id ||= 2029 if self.diagnostic_id.nil?
  end

  def self.totalappointment
    if (:status_id == 4)
    @totalapps = Appointment.count
    end
  end

end

app/models/diagnostic.rb
class Diagnostic < ActiveRecord::Base

  has_many :appointments

end

app/models/employee.rb
class Employee < ActiveRecord::Base

  has_one :user
  belongs_to :state

  def self.emailcheck
    if Patient.where(userid: self.userid).exists? then
      errors.add(:userid,'This email is already in use. Please use another.')
    end
  end
end

app/models/insurance.rb
class Insurance < ActiveRecord::Base

  has_many :patients

end

app/models/patient.rb
class Patient < ActiveRecord::Base

  belongs_to :insurance
  has_many :physicians , :through => :appointments
  has_many :appointments
  has_one :user
  belongs_to :state

  def self.emailcheck
    if Patient.where(userid: self.userid).exists? then
      errors.add(:userid,'This email is already in use. Please use another.')
    end
  end

  def self.emailval
    validates_uniqueness_of :email
  end

  # Donor.joins(:donations).where(:id => params[:id]).sum('value'))


end

app/models/physician.rb
class Physician < ActiveRecord::Base

  has_one :user
  has_many :patients, :through => :appointments
  has_many :appointments
  belongs_to :state

  def self.emailcheck
    if Patient.where(userid: self.userid).exists? then
      errors.add(:userid,'This email is already in use. Please use another.')
    end
  end
end

app/models/state.rb
class State < ActiveRecord::Base

  has_many :patients
  has_many :physicians
  has_many :employees

end

app/models/status.rb
class Status < ActiveRecord::Base

  has_many :appointments

end

app/models/user.rb
class User < ActiveRecord::Base

  belongs_to :patient
  belongs_to :physician
  belongs_to :employee

  enum role: [:admin, :physician, :patient, :employee]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :patient
  end

  def self.emailval
    validates_uniqueness_of :email
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!

  def index
    if user_signed_in?
        redirect_to  :controller=>'dashboard', :action => 'index'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper



end

app/helpers/apps_helper.rb
module AppsHelper
end

app/helpers/diagnostics_helper.rb
module DiagnosticsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/insurance_helper.rb
module InsuranceHelper
end

app/helpers/insurances_helper.rb
module InsurancesHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/physicians_helper.rb
module PhysiciansHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/shared/_sidebar.html.erb
<% if user_signed_in? %>
    <body class="main" style="background-image: url(<%= asset_path 'grey.jpg' %>)"  >


<div id="wrapper">


  <!-- Sidebar -->
  <div id="sidebar-wrapper">

    <ul class="sidebar-nav">

      <% if current_user.admin? %>
      <li>
        <%= link_to('Appointments', appointments_path) %>
      </li>
      <li>
        <%= link_to('Patients', patients_path) %>
      </li>
      <li>
        <%= link_to('Physicians', physicians_path) %>
      </li>
      <li>
        <%= link_to('Diagnostics', diagnostics_path) %>
      </li>
      <li>
        <%= link_to('Employees', employees_path) %>
      </li>
      <li>
        <%= link_to('Insurances', insurances_path) %>
      </li>
      <li>
        <%= link_to('Data Management', datamanage_index_path) %>
      </li>
      <% elsif current_user.physician? %>
              <li>
                <%= link_to('New Information', new_physician_path) %>
              </li>
              <li>
                <%= link_to('My Information', physicians_path) %>
              </li>
              <li>
                <%= link_to('My Appointments', appointments_path) %>
              </li>
      <% elsif current_user.patient? %>
          <li>
            <%= link_to('New Information', new_patient_path) %>
          </li>
          <li>
            <%= link_to('My Appointments', appointments_path) %>
          </li>
          <li>
            <%= link_to('My Information', patients_path) %>
          </li>
      <% elsif current_user.employee? %>
          <li>
            <%= link_to('New Information', new_employee_path) %>
          </li>
          <li>
            <%= link_to('Appointments', appointments_path) %>
          </li>
          <li>
            <%= link_to('My Information', employees_path) %>
          </li>
      <% end %>

    </ul>
  </div>

</div>

<script src="bootstrap/jquery.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src="bootstrap/bootstrap.min.js"></script>


<!--/span-->
</body>


<% else %>
    <body class="main" style="background-image: url(<%= asset_path 'island.jpg' %>)"  >
<% end %>